# Build NodeJS Express app using Azure Pipelines
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript?view=vsts
pool:
  vmImage: 'Ubuntu 16.04'
  
steps:
- task: NodeTool@0
  inputs:
    versionSpec: '8.x'
  
- task: Npm@1
  displayName: 'npm install'
  inputs:
    command: install

- task: Npm@1
  displayName: 'npm run test:uni'
  inputs:
    command: custom
    customCommand: 'test:unit'

- task: Npm@2
  displayName: 'npm run test:e2e'
  inputs:
    command: custom
    customCommand: 'test:e2e'

- task: Npm@3
  displayName: 'npm run build'
  inputs:
    command: custom
    customCommand: 'build'
    
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
    includeRootFolder: false

- task: PublishBuildArtifacts@1